version: '3'
services:
        web:
                image: flask_sass
                build: .
                ports:
                        - "8036:8080"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
